'''Create a Python class for a paint brush that has the following properties:

Size (small, medium, or large)
Color (red, blue, green, or yellow)
Brand (Winsor & Newton, Liquitex, or Grumbacher)
Type (round or flat) # Im painting with medium with colour blue, Wnsor and newton and  round.
'''

In [4]:
class creat_list:
    def __init__(self):
    def get_result(self):
        l=[]
        for i in range(1,6):
            l.append(i)
        print(l)
l2=creat_list()
l2.get_result()

IndentationError: expected an indented block after function definition on line 2 (1897646160.py, line 3)

In [3]:
class total_notes:
    def __init__(self,amount):
        self.amount=amount
    def get_count_notes(self):
        notes_no=[500,200,100,50,20,10]
        for i in range(0,6):
            if self.amount>=i:
                l1=self.amount//i
                self.amount%=i
                total_notes=sum(500,200,100,50,20,10)
                print(total_notes)
n1=total_notes(int(input()))
n1.get_count_notes()

880


ZeroDivisionError: integer division or modulo by zero

In [4]:
name = "John"
age = 25
result = "My name is " + name + " and I am " + age + " years old."

TypeError: can only concatenate str (not "int") to str

In [1]:
class paint_brush:
    def __init__(self,size,colour,brand,type):
        self.size=size
        self.colour=colour
        self.brand=brand
        self.type=type
    def get_paint_in_class(self):
        print(f"Im painting with {self.size} with {self.colour},{self.brand} and{self.type}")

brush=paint_brush(size="medium",colour="red",brand="liquitex",type="flat")
brush.get_paint_in_class()



Im painting with medium with red,liquitex andflat


In [ ]:
ist=input()
max_number=0
for i in list:
    if i>max_number:
        max_number=i
        print(max_number)



In [ ]:
ist=input()
max_number=0
for i in list:
    if i>max_number:
        max_number=i
        print(max_number)


In [4]:
def_max_num_in_list():
    max_num=list[0]
    for i in list:
        if i>max_num:
            max_num=i
    return max_num

list=eval(input())
print(max_num_in_list(list))



SyntaxError: invalid syntax (2924054741.py, line 1)

In [1]:
str=input()
n=int(input())
result=str*n
print(result)

abcabc


In [5]:
def longest_word(word_list):
    word_len=[]
    for i in word_list:
        word_len.append( len(i))
    return max(word_len),word_list[word_len.index(min(word_len))]
word_list=list(input().split(" "))
print(longest_word(word_list))



(6, 'ok')


In [ ]:
def pascal_triangle(n):
       throw=[1]
       y=[0]
       for x in range(max(n,0)):
            print(x)
            throw=[l+r for l,r in zip(y+[throw],[throw+y])]
       return n>=1
n=int(input())


In [10]:
def odd_values_string(str1):
     result = " "" " 
     for i in range(len(str1)): 
        if i % 2 == 0:
             result = result + str1[i] 
     return result

str1 = input()
print(odd_values_string(str1))

  prmte


In [15]:
def add_str(str):
    if len(str)>2:
        if str[-3]=="ing":
            str+="ly"
        else:
            str+="ing"
str=input()


In [23]:
def add_string(str1): 

  if len(str1) > 2: 
    if str1[-3:] == 'ing': 
        str1 += 'ly' 
    else: 
        str1 += 'ing'
    return str1
str1=input()
print(add_string(str1))

flyingly


In [26]:
def add_string(str1): 

  if len(str1) > 2: 
    if str1[-3:] == 'ing': 
        str1 += 'ly' 
    else: 
        str1 += 'ing'
    return str1
str1=input()
print(add_string(str1))

lyingly


In [30]:
def find_charecter(a,b):
    new_a=b[:2]+a[2:]
    new_b=a[:2]+b[2:]
    return  new_a+" "+ new_b
a=input()
b=input()
print(find_charecter(a,b))

In [1]:
def find_charecter(a,b):
    new_a=b[:2]+a[2:]
    new_b=a[:2]+b[2:]
    return  new_a+" "+ new_b
a=input()
b=input()
print(find_charecter(a,b))

In [29]:
def char_frequency(str1):
    dict={}
    for n in str1:
        keys=dict.keys()
        if n in keys:
           dict[n]+=1
        else:
           dict[n]=1
    return dict
str=input()
print(char_frequency(str1))


{'l': 1, 'y': 1, 'i': 1, 'n': 1, 'g': 1}


In [14]:
def remove_cahr(str,n):
    first_part=str[:n]
    last_part=str[n+1:]
    return first_part+last_part
str=input()
n=int(input())
print(remove_cahr(str,n))


ython


In [25]:
def add_str(str):
    if len(str)>2:
        if str[-3]=="ing":
            str+="ly"
        else:
            str+="ing"
    return str
str=input()
print(add_str(str))

lyinging


In [15]:
str=input()
print(str[-1]+str[1:-1]+str[:1])

ariyp


In [18]:
def odd_str(str):
    result = """"
    for i in range(len(str)):
      if i%2==0:
        result=result+str[i]
    return result
str=input()
print(odd_str(str))

SyntaxError: incomplete input (158718669.py, line 2)

In [19]:
def odd_values_string(str1):
     result = """" 
     for i in range(len(str1)): 
        if i % 2 == 0: 
            result = result + str1[i] 
        return result

str1 = input() 
print(odd_values_string(str1))

SyntaxError: incomplete input (3624676799.py, line 2)

In [3]:
from PIL import Image
import IO
with open("sample2.png", 'rb) as f:
  binary_data=f.read()
  img=Image.open(IO.BytesIO(binary_data))
  print(img.size())
  rot=img.rotata(90)


SyntaxError: unterminated string literal (detected at line 3) (2998993423.py, line 3)

In [6]:
import pandas as pd
csv=pd.to_read(C:\Users\HP\Downloads\employee.csv)
print(csv)

SyntaxError: invalid syntax (3953835548.py, line 2)

In [12]:
str=input()
n=input()
str2=" "
for i in str:
    i.remove[0]
    str2.append(i)
    print(str2)

AttributeError: 'str' object has no attribute 'remove'

In [ ]:
x = [1, 2, 3, 4, 5]
print(x[5])

In [ ]:
list=eval(input())
num=int(input())
if num in list:
   print("True")

In [1]:
def factorial(n):
    if n==0:
      return 1
    else:
      return n*factorial(n-1)
n=int(input())
if n<0:
   print("its does not exits")
elif n==0:
   print("the factorial of 0 is 1")
else:
   print(factorial(n))

2


In [2]:
def fibonacci(n):
    if n == 0:
        return 0
    elif n == 1:
        return 1
    else:
        return fibonacci(n-1) + fibonacci(n-2)

print(fibonacci(7))

13


In [3]:
def countdown(n):
    if n == 0:
        print("Blastoff!")
    else:
        print(n)
        countdown(n-1)
countdown(4)

4
3
2
1
Blastoff!


In [4]:
def print_numbers(n):
    if n == 0:
        return
    else:
        print_numbers(n-1)
        print(n)

print_numbers(3)



1
2
3


In [2]:
def trimonacci_sequence(n):
    if n==0 or n==1:
        return 0
    elif n==2:
        return 1
    else:
        return  trimonacci_sequence(n-1)+trimonacci_sequence(n-2)+trimonacci_sequence(n-3)

n=(int(input())) 
 
if n<0:
    print("negative  integer does  not exits")
else:
    print(trimonacci_sequence(5))

4


In [5]:
def palindrom(s):
    if len(s)<1:
        return True
    else:
        if s[0]==s[-1]:
            return palindrom(s[1:-1])
        else:
            return False
num=str(input())
if palindrom(num)==True:
    print("its a palandrom")
else:
    print("its not a palendrom")

its a palandrom


In [7]:
def count_path(row,col,m,n):
    if row==(m-1) and col==(n-1):
        return 1
    if row >= m and col >= n:
        return 0
    right_count_path=count_path(row,col+1,m,n)
    left_count_path=count_path(row+1,col,m,n)
    return right_count_path+left_count_path
m,n=3,3
total_count_path=count_path(0,0,m,n)
print(total_count_path)

RecursionError: maximum recursion depth exceeded

In [8]:
def find_data(arr, target, i=0):
    if i == len(arr):
        return False
    elif arr[i] == target:
        return True
    else:
        return find_data(arr, target, i+1)

arr = [1, 2, 3, 4, 5]
target = 6
print(find_data(arr, target))

False


In [9]:
def subsequence(inp, out):
    if len(inp) == 0:
        print(out)
        return
    subsequence(inp[1:], out + inp[0])
    subsequence(inp[1:], out)

subsequence("xyz", "")

xyz
xy
xz
x
yz
y
z



In [10]:
def fibonacci(n):
    if n == 0:
        return 0
    elif n == 1:
        return 1
    else:
        return fibonacci(n-1) + fibonacci(n-2)

print(fibonacci(7))

13


In [11]:
def display(arr, index):
    if index < len(arr):
        display(arr, index+1)
        print(arr[index], end=" ")

arr = [1, 2, 3, 4, 5]
display(arr, 0)

5 4 3 2 1 

In [12]:
def find_data(arr, target):
    if len(arr) == 0:
        return False
    elif arr[-1] == target:
        return True
    else:
        return find_data(arr[:-1], target)

arr = [1, 2, 3, 4, 5]
target = 3
print(find_data(arr, target))

True


In [4]:
def bubble_sort(N):
    n=len(N)
    for i in range(n):
        for j in range(0,n-i-1):
            if N(j) > N(j+1):
                N(j),N(j+1)==N(j+1),N(j)
N=[5,3,6,1,4,2,8]
bubble_sort(N)
for i in range(len(N)):
    print("%d"%N(i))


TypeError: 'list' object is not callable

In [9]:
def liner_search(data,target):
    for i in range(len(data)):
        if data(i)==target:
            return 1
    return-1
data = list(map(int, input("Enter the list of data, separated by spaces: ").split()))
target=int(input("Enter the target value here:"))
index=liner_search(data,target)
if index!=-1:
    print(f"target{target} at index is{index}")
else:
    print(f"{target} is not found in data")

ValueError: invalid literal for int() with base 10: '1,2,3,4,5,6'

In [1]:
import numpy as np
arr=np.random.randint(1,100,size=10)
arr_sorted=np.sort(arr)
print(arr)
print(arr_sorted)

[27 74 31 76 41 23 24 83 17 60]
[17 23 24 27 31 41 60 74 76 83]


In [3]:
import numpy as np

# Create an array with values from 0 to 9
arr = np.arange(10)

# Create an array with values from 5 to 9 with a step of 2
arr2 = np.arange(5, 10, 2)
print(arr)
print(arr2)

[0 1 2 3 4 5 6 7 8 9]
[5 7 9]


In [4]:
import numpy as np

# Create an array with 5 values between 0 and 1
arr = np.linspace(0, 1, 5)
print(arr)

[0.   0.25 0.5  0.75 1.  ]


In [5]:
import numpy as np

# Create a 1-dimensional array
arr1d = np.arange(10)

# Reshape the array to a 2-dimensional array with 2 rows and 5 columns
arr2d = arr1d.reshape(2, 5)
print(arr1d)
print(arr2d) 

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [7]:
import numpy as np

# Create a 1-dimensional array
arr1d = np.arange(10)

# Reshape the array to a 2-dimensional array with 2 rows and 5 columns
arr2d = arr1d.reshape(2, 5)
print(arr1d)
print(arr2d)


[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [8]:
import numpy as np

# Create a 2-dimensional array
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Transpose the array
arr_transpose = np.transpose(arr2d)
print(arr2d)
print(arr_transpose)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [12]:
import pandas as pd
d2_ARRAY=np.random.randint(4,6,(3,4))
first_dataframe=pd.DataFrame(d2_ARRAY,columns=["akshay","radha","prathvik","sanj"])
print(d2_ARRAY)
print(first_dataframe)

[[4 4 4 5]
 [5 4 4 5]
 [4 4 5 5]]
   akshay  radha  prathvik  sanj
0       4      4         4     5
1       5      4         4     5
2       4      4         5     5


In [2]:

import numpy as np

# create a 3D numpy array
arr3d = np.array([[[1, 2, 3],
                   [4, 5, 6]],

                  [[7, 8, 9],
                   [10, 11, 12]]])

# slice the first matrix of the array
mat1 = arr3d[0, :, :]
print(mat1)

# slice the second column of the first matrix of the array
col2 = arr3d[0, :, 1]
print(col2)
# slice a subarray from the original array
subarr = arr3d[1, 0:2, 0:2]
print(subarr)

[[1 2 3]
 [4 5 6]]
[2 5]
[[ 7  8]
 [10 11]]


In [13]:
import pandas as pd
import numpy as np
import random
arry2d=np.random.randint(2,3,(3,4))
df=pd.DataFrame(arry2d,columns=["a","b","c","d"])
print(df)

   a  b  c  d
0  2  2  2  2
1  2  2  2  2
2  2  2  2  2


In [14]:
df=pd.DataFrame(arry2d,columns=["a","b","c"])

ValueError: Shape of passed values is (3, 4), indices imply (3, 3)

In [15]:
list_of_dic={"name":("prinya","riya","shreya"),"age":("12","10")}
df=pd.DataFrame(list_of_dic)
print(df)

ValueError: All arrays must be of the same length

In [16]:
actor=["ram_lakhan","kanchi","mehendi"]
actor_age=[34,55]
actors=list(zip(actor,actor_age))
df=pd.DataFrame(actors,columns=["name","age"])
print(df)


         name  age
0  ram_lakhan   34
1      kanchi   55


In [19]:
imdb_df=pd.read_csv("C:\Users\HP\Desktop\alma\Capstone_Project_Introduction_to_Computer_Programming.ipynb")
imdb_df.head()                               

SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape (915442294.py, line 1)

In [21]:
import numpy as np
fruits = np.array(["Apple", "Banana", "Cherry", "Dragonfruit", "Elderberry"])
quantity_sold = np.array([100, 200, 50, 75, 150])
price_per_unit = np.array([0.5, 0.25, 1, 1.5, 2])
total_sales=np.sum(quantity_sold)
total_average=np.mean(price_per_unit)
print(total_sales)
print(total_average)

575
1.05


In [24]:
sales = np.array([100, 200, 150, 75, 250, 300, 175, 225, 125, 275])
mean_sales=np.mean(sales)
print(mean_sales)
median_sales=np.median(sales)
print(median_sales)
std_sales=np.std(sales)
print(std_sales)
from scipy import stats
mode_sales=np.mode(sales)
print(mode_sales)



187.5
187.5
71.80703308172536


ModuleNotFoundError: No module named 'scipy'

In [30]:
import pandas as pd
data = {'Product': ['Shirts', 'Pants', 'Jackets', 'Shoes'],
        'Sales': [100, 75, 50, 25]}

df=pd.DataFrame(data)
print(pd)
average_sales=pd.DataFrame(data,sales)
print(average_sales)

<module 'pandas' from 'C:\\Users\\HP\\AppData\\Roaming\\Python\\Python312\\site-packages\\pandas\\__init__.py'>


ValueError: Length of values (4) does not match length of index (10)

In [31]:
import pandas as pd
books_dict = {
    'Title': ['Book A', 'Book B', 'Book C', 'Book D', 'Book E'],
    'Author': ['Author X', 'Author Y', 'Author X', 'Author Z', 'Author Y'],
    'Year of Publication': [2005, 2010, 2002, 2015, 2018],
    'Number of Pages': [300, 250, 180, 400, 320]
}
dict_df=pd.DataFrame(books_dict)
print(dict_df)

    Title    Author  Year of Publication  Number of Pages
0  Book A  Author X                 2005              300
1  Book B  Author Y                 2010              250
2  Book C  Author X                 2002              180
3  Book D  Author Z                 2015              400
4  Book E  Author Y                 2018              320


In [32]:
dict_df.head(5)

Title    Author  Year of Publication  Number of Pages
0  Book A  Author X                 2005              300
1  Book B  Author Y                 2010              250
2  Book C  Author X                 2002              180
3  Book D  Author Z                 2015              400
4  Book E  Author Y                 2018              320

In [40]:
dict_df.tail(3)
dict_df.Rows

AttributeError: 'DataFrame' object has no attribute 'Rows'

In [39]:
dict_df.rows

AttributeError: 'DataFrame' object has no attribute 'rows'

In [42]:
# Create a DataFrame
data = {'name': ['Alice', 'Bob', 'Charlie'],
        'age': [25, 30, 35]}
df = pd.DataFrame(data)

# Write the DataFrame to a CSV file
df.to_csv('newframe.csv', index=True)
print(df)


#Check out the files tab on the left for the file.

      name  age
0    Alice   25
1      Bob   30
2  Charlie   35


In [36]:
from google.colab import drive
import pandas as pd
import numpy as np
read=pd.read_csv("imdb_data.csv")
print(read)



ModuleNotFoundError: No module named 'google'

In [9]:

from google.colab import drive
drive.mount('/content/drive')
import pandas as pd
import numpy as np
def revised_profile(revanue,budget):
 if revanue>0:
  new_profit=revanue-budget
 else:
  new_profit=np.nan
 return new_profit

imdb_df['new_profit'] = imdb_df.apply(lambda x: revised_profit(x['revenue'], x['budget']),axis=1)
imdb_df["new_profit"].head()

ModuleNotFoundError: No module named 'google'

In [7]:
import pandas as pd 
dic={
    "name":["priya","riya","roshani","priyansh"],
    "age":[23,24,45,2]
}
df=pd.DataFrame(dic)
print(df)
df.to_csv("mix.csv")

       name  age
0     priya   23
1      riya   24
2   roshani   45
3  priyansh    2


In [7]:
import numpy as np
a=np.array([1,2,3,4,5])
b=np.array([3,4,5,6,7])
dot_product=0
for i in range(len(a)):
  dot_product+=a[i]*b[i]

print(dot_product)

85


In [6]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

dot_product = 0
for i in range(len(a)):
    dot_product += a[i] * b[i]
print(dot_product)

32


In [8]:
dot_product=np.dot(a,b)
print(dot_product)

85


In [10]:
from joblib import Memory
mem=Memory(location="cache")
@mem.cache
def cal_mean(num):
    total=sum(num)
    return total/len(num)
my_list=[1,2,3,4,5]
mem1=cal_mean(my_list)
mem2=cal_mean(my_list)
print(mem1)
print(mem2)


ModuleNotFoundError: No module named 'joblib'

In [11]:
from joblib import Memory

# create a Memory object to cache function calls
mem = Memory(location='cache')

# define a function to calculate the mean of a list of numbers
@mem.cache
def calc_mean(numbers):
    print("Calculating mean...")
    total = sum(numbers)
    return total / len(numbers)

# define a list of numbers to use for testing
my_list = [1, 2, 3, 4, 5]

# call the function the first time, which will calculate the mean and cache the result
result1 = calc_mean(my_list)



ModuleNotFoundError: No module named 'joblib'

In [13]:
import pandas as pd
from pandarallel import pandarallel
pandarallel.initialize()
df=pd.DataFrame({"a":[1,2,3,4,5],"b":[4,5,6,7,8]})
def my_fuc(row):
    return row["a"]+row["b"]
result=df.parallel_apply(my_fuc,axis=1)
print(result)

INFO: Pandarallel will run on 2 workers.
INFO: Pandarallel will use standard multiprocessing data transfer (pipe) to transfer data between the main process and workers.

https://nalepae.github.io/pandarallel/troubleshooting/
0     5
1     7
2     9
3    11
4    13
dtype: int64


In [26]:
import threading
import time
def task(name):
    print(f"starting task{name}")
    time.sleep(2)
    print(f"ending task{name}")
if __name__=="__main__":
    threads = [threading.Thread(target=task, args=(i,)) for i in range(5)]
for t in threads:
    t.start()
for t in threads:
    t.join()
print("all task is completed")
   


starting task0
starting task1
starting task2
starting task3
starting task4
ending task0ending task1

ending task2
ending task3
ending task4
all task is completed


In [ ]:
50

In [2]:
import json
with open(HP\Downloads\employee.json) as f:
    data=json.load(f)
print(data)

SyntaxError: unexpected character after line continuation character (1214643854.py, line 2)